name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NEXT_APP_EMAIL: ${{ secrets.NEXT_APP_EMAIL }}
          NEXT_APP_PWD: ${{ secrets.NEXT_APP_PWD }}
        run: |
          echo "NEXT_APP_EMAIL: $NEXT_APP_EMAIL"
          echo "NEXT_APP_PWD: $NEXT_APP_PWD"
          npm run build

      - name: Create .env file
        run: |
          echo "NEXT_APP_EMAIL=${{ secrets.NEXT_APP_EMAIL }}" >> .env
          echo "NEXT_APP_PWD=${{ secrets.NEXT_APP_PWD }}" >> .env

      - name: Transfer .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: .env
          target: /home/ubuntu/app

      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: .
          target: /home/ubuntu/app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            npm install
            npm run build
            pm2 stop all || true
            pm2 start npm -- start
            pm2 save
            find /home/ubuntu/app -name "*.tar.gz" -type f -delete
            exit
